// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: api/fibo.proto

package fibogrpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FibonacciRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From uint32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   uint32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *FibonacciRangeRequest) Reset() {
	*x = FibonacciRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_fibo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibonacciRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonacciRangeRequest) ProtoMessage() {}

func (x *FibonacciRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fibo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonacciRangeRequest.ProtoReflect.Descriptor instead.
func (*FibonacciRangeRequest) Descriptor() ([]byte, []int) {
	return file_api_fibo_proto_rawDescGZIP(), []int{0}
}

func (x *FibonacciRangeRequest) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *FibonacciRangeRequest) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

type FibonacciRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*FibonacciNumber `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *FibonacciRangeResponse) Reset() {
	*x = FibonacciRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_fibo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibonacciRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonacciRangeResponse) ProtoMessage() {}

func (x *FibonacciRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fibo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonacciRangeResponse.ProtoReflect.Descriptor instead.
func (*FibonacciRangeResponse) Descriptor() ([]byte, []int) {
	return file_api_fibo_proto_rawDescGZIP(), []int{1}
}

func (x *FibonacciRangeResponse) GetList() []*FibonacciNumber {
	if x != nil {
		return x.List
	}
	return nil
}

type FibonacciNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N     uint32 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FibonacciNumber) Reset() {
	*x = FibonacciNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_fibo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibonacciNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonacciNumber) ProtoMessage() {}

func (x *FibonacciNumber) ProtoReflect() protoreflect.Message {
	mi := &file_api_fibo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonacciNumber.ProtoReflect.Descriptor instead.
func (*FibonacciNumber) Descriptor() ([]byte, []int) {
	return file_api_fibo_proto_rawDescGZIP(), []int{2}
}

func (x *FibonacciNumber) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *FibonacciNumber) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_api_fibo_proto protoreflect.FileDescriptor

var file_api_fibo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x62, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x66, 0x69, 0x62, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x3b, 0x0a, 0x15, 0x46, 0x69,
	0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x16, 0x46, 0x69, 0x62, 0x6f, 0x6e,
	0x61, 0x63, 0x63, 0x69, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x66, 0x69, 0x62, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x62, 0x6f, 0x6e,
	0x61, 0x63, 0x63, 0x69, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0x35, 0x0a, 0x0f, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x5a, 0x0a, 0x09, 0x46, 0x69, 0x62, 0x6f, 0x6e,
	0x61, 0x63, 0x63, 0x69, 0x12, 0x4d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x1f, 0x2e, 0x66, 0x69, 0x62, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x62, 0x6f,
	0x6e, 0x61, 0x63, 0x63, 0x69, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x66, 0x69, 0x62, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x62,
	0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x2f, 0x66, 0x69, 0x62, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_fibo_proto_rawDescOnce sync.Once
	file_api_fibo_proto_rawDescData = file_api_fibo_proto_rawDesc
)

func file_api_fibo_proto_rawDescGZIP() []byte {
	file_api_fibo_proto_rawDescOnce.Do(func() {
		file_api_fibo_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_fibo_proto_rawDescData)
	})
	return file_api_fibo_proto_rawDescData
}

var file_api_fibo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_fibo_proto_goTypes = []interface{}{
	(*FibonacciRangeRequest)(nil),  // 0: fibogrpc.FibonacciRangeRequest
	(*FibonacciRangeResponse)(nil), // 1: fibogrpc.FibonacciRangeResponse
	(*FibonacciNumber)(nil),        // 2: fibogrpc.FibonacciNumber
}
var file_api_fibo_proto_depIdxs = []int32{
	2, // 0: fibogrpc.FibonacciRangeResponse.list:type_name -> fibogrpc.FibonacciNumber
	0, // 1: fibogrpc.Fibonacci.GetRange:input_type -> fibogrpc.FibonacciRangeRequest
	1, // 2: fibogrpc.Fibonacci.GetRange:output_type -> fibogrpc.FibonacciRangeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_fibo_proto_init() }
func file_api_fibo_proto_init() {
	if File_api_fibo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_fibo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibonacciRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_fibo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibonacciRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_fibo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibonacciNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_fibo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_fibo_proto_goTypes,
		DependencyIndexes: file_api_fibo_proto_depIdxs,
		MessageInfos:      file_api_fibo_proto_msgTypes,
	}.Build()
	File_api_fibo_proto = out.File
	file_api_fibo_proto_rawDesc = nil
	file_api_fibo_proto_goTypes = nil
	file_api_fibo_proto_depIdxs = nil
}
